name: cloning git code 
on: [push]
jobs:
  cloning_git: 
    runs-on: ubuntu-latest 
    steps: 
      - name: "cloning git  code" 
        uses: actions/checkout@v7
        

  

            
      
      
  
