name: cloning repo 
on: [push,workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "cloning code" 
        run: |
          echo "cloning code" 
          echo "${{toJson(github)}}"
          git clone https://github.com/${{github.repository}}.git
   

            
      
      
  
