name: cloning git code 
on: [push,workflow_dispatch]
jobs:
  test: 
    runs-on: ubuntu-latest 
    steps: 
      - name: "cloning git  code" 
        uses: actions/checkout@v7
      - name: "check npm version"
        run: node -v 
      - name: "install node 20 version" 
        uses: actions/setup-node@v7  
        with: 
           node-version: '20' 
      - name: "install dependency"
        run: npm ci 
      - name: "run tests" 
        run: npm run test  
  depoy:
    runs-on: ubuntu-latest 
    steps: 
      - name: "cloning git  code" 
        uses: actions/checkout@v7
      - name: "check npm version"
        run: node -v 
      - name: "install node 20 version" 
        uses: actions/setup-node@v7  
        with: 
           node-version: '20' 
      - name: "install dependency"
        run: npm ci 
      - name: "run tests" 
        run: npm run test  
      - name: "build npm project" 
        run: pnm run build 
      - name: "depoyed application" 
        run: echo "deployment successful ...."    
           

  
  

            
    
      
  
