name: Deployed npm project 
on: [workflow_dispatch]
jobs:
    cloning_code:
        runs-on: ubuntu-latest 
        steps:
            - name: "cloning git code" 
              uses: actions/checkout@v7
            - name: "install pnm version" 
              uses: actions/setup-node@v7
              with: 
                node-version: '20'
            - name: "install dependencies" 
              run: npm ci 
            - name: "run tests" 
              run: npm run test 
            - name: "build project" 
              run: npm run build       
            - name: "Deploy aspplication"
              run: echo "Deployment success...."         